site_name: PINN-ADT

hidden: "internal_endpoints.md"

nav:
  - Главная: "index.md"
  - Руководство:
    - Начало работы: "guide/getting_started.md"
    - Ансамблирование: "guide/ensemble.ipynb"
  - API:
    - PINN: "api/PINN.md"
    - Neural Network: "api/neural_network.md"
    - Callbacks: "api/callbacks.md"
    - Problems: "api/problems.md"
    - Ensemble: "api/ensemble.md"
    - Generation: "api/generation.md"
    - Geometry: "api/geometry.md"
    - Trainer: "api/trainer.md"
    - Regularization: "api/regularization.md"
    - Mesh: "api/mesh.md"
  - Как писать документацию: "how_to_use.md"

theme:
  name: material

plugins:
    - mkdocs-jupyter