site_name: PINN-ADT

hidden: "internal_endpoints.md"

nav:
  - Главная: "index.md"
  - Руководство:
      - Начало работы: "guide/getting_started.md"
      - Ансамблирование: "guide/ensemble.ipynb"
  - API:
      - PINN: "api/PINN.md"
      - Neural Network: "api/neural_network.md"
      - Callbacks: "api/callbacks.md"
      - Problems: "api/problems.md"
      - Ensemble: "api/ensemble.md"
      - Generation: "api/generation.md"
      - Geometry: "api/geometry.md"
      - Trainer: "api/trainer.md"
      - Regularization: "api/regularization.md"
      - Mesh: "api/mesh.md"
      - Utils: "api/utils.md"
  - Как писать документацию: "how_to_use.md"

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

plugins:
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
